version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "8437:8437"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=execute
      - DB_PASSWORD=execute
      - DB_NAME=execute_db
      - DB_SSLMODE=disable
    restart: on-failure
    
  frontend:
    build: ./web
    container_name: frontend
    ports:
    - "5173:5173"
    restart: on-failure

  db:
    image: postgres:17.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: execute
      POSTGRES_PASSWORD: execute
      POSTGRES_DB: execute_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: